import { useMutation, gql } from '@apollo/client';
import type { ApolloCache, Reference } from '@apollo/client';
import { useCurrentUser } from './useCurrentUser';

// Placeholder mutation document — in the real app this is generated by
// GraphQL codegen from the schema.
const STAR_COURSE = gql`
  mutation StarCourse($courseId: ID!) {
    starCourse(courseId: $courseId) {
      id
    }
  }
`;

export function useStarredCourse(courseId: string) {
  const [starCourse, { loading }] = useMutation(STAR_COURSE);
  const { id: userId } = useCurrentUser();

  const toggleStar = async () => {
    await starCourse({
      variables: { courseId },
      update(cache: ApolloCache<unknown>) {
        const userRef = cache.identify({ __typename: 'User', id: userId });
        const courseRef: Reference = { __ref: `Course:${courseId}` };

        cache.modify({
          id: userRef,
          fields: {
            starredCourses(existingRefs: readonly Reference[] = []) {
              const alreadyStarred = existingRefs.some(
                (ref) => ref.__ref === courseRef.__ref
              );
              return alreadyStarred ? existingRefs : [...existingRefs, courseRef];
            }
          }
        });
      }
    });
  };

  return { toggleStar, loading };
}
